include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    invalid_assignment: warning

linter:
  rules:
    # --- Kod Temizliği ve Performans ---
    - unnecessary_const
    - unnecessary_new
    - unnecessary_string_interpolations
    - unnecessary_lambdas

    # --- Sabitler ve Optimizasyon ---
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

    # --- Okunabilirlik ve Standartlar ---
    - prefer_single_quotes
    - avoid_empty_else
    - empty_catches