include: package:flutter_lints/flutter.yaml

analyzer:
  # 'plugins' anahtarı artık buranın (analyzer bloğunun) altında yer almalı
  plugins:
    - custom_lint

  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
    invalid_assignment: warning
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # --- Performans ve Bellek Optimizasyonu ---
    - unnecessary_const
    - unnecessary_new
    - unnecessary_string_interpolations
    - unnecessary_lambdas
    - avoid_unnecessary_containers
    - sized_box_for_whitespace

    # --- Sabitler ve Değişken Disiplini ---
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals

    # --- Güvenlik ve Mimari Hatalarını Önleme ---
    - use_build_context_synchronously
    - avoid_print
    - avoid_returning_null_for_void

    # --- Kod Düzeni ve Standartlar ---
    - prefer_single_quotes
    - avoid_empty_else
    - empty_catches
    - prefer_relative_imports
    - prefer_is_empty
    - sort_child_properties_last
    - prefer_is_not_empty
    - prefer_collection_literals
    - unnecessary_getters_setters
    - prefer_conditional_assignment
    - prefer_null_aware_operators
    - prefer_iterable_whereType
    - unnecessary_parenthesis
    - prefer_contains
    - unnecessary_string_escapes
    - unnecessary_late
    - prefer_interpolation_to_compose_strings
    - slash_for_doc_comments